/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package SourcePackage

import spock.lang.Specification
import static org.junit.jupiter.api.Assertions.assertEquals

class AppTest extends Specification {

    def "count number of elements should throw exception if list parameter is null"() {
        setup:
            def list = null

        when:
            def result = App.countNumberOfElements(list)

        then:
            thrown(NullPointerException)
    }

    def "test count number of elements should correct run parameter is list"() {
        setup:
            def actual = ['a', 'b', 'c', 'd', 'a', 'b', 'c']
            def expected = ['a': 2, 'c': 2, 'b': 2, 'd': 1]

        when:
            def result = App.countNumberOfElements(actual)

        then:
            assertEquals(expected, result);
    }
}
